[package]
name = "cop-rs"
version = "0.1.0"
authors = ["Michael FÃ¤rber <michael.faerber@gedenkt.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
log = "0.4"
tptp = "0.24"
